import {
  HomeOutlined,
  AppstoreOutlined,
  SettingOutlined,
  UserOutlined,
  TeamOutlined,
  CloudOutlined,
  DatabaseOutlined,
  FileOutlined,
  FolderOutlined,
  MonitorOutlined,
  SafetyOutlined,
  AuditOutlined,
  ToolOutlined,
  DashboardOutlined,
  BarChartOutlined,
  PieChartOutlined,
  LineChartOutlined,
  TableOutlined,
  FormOutlined,
  ProfileOutlined,
  UnorderedListOutlined,
  SearchOutlined,
  FilterOutlined,
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  ReloadOutlined,
  DownloadOutlined,
  UploadOutlined,
  ExportOutlined,
  ImportOutlined,
  CheckOutlined,
  CloseOutlined,
  LockOutlined,
  UnlockOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  MailOutlined,
  PhoneOutlined,
  MessageOutlined,
  NotificationOutlined,
  BellOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  CodeOutlined,
  ConsoleSqlOutlined,
  EnvironmentOutlined,
  FileAddOutlined,
  FileTextOutlined,
  GlobalOutlined,
  HistoryOutlined,
  IdcardOutlined,
  LinkOutlined,
  MenuOutlined,
  PaperClipOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SyncOutlined,
  ApartmentOutlined,
  BranchesOutlined,
  NodeIndexOutlined,
  DeploymentUnitOutlined,
  ClusterOutlined,
  FieldNumberOutlined,
} from '@ant-design/icons';
import type { ComponentType, ReactNode } from 'react';

/** 常用图标白名单 — 覆盖菜单和页面常用场景，按需扩展 */
const iconMap: Record<string, ComponentType> = {
  HomeOutlined,
  AppstoreOutlined,
  SettingOutlined,
  UserOutlined,
  TeamOutlined,
  CloudOutlined,
  DatabaseOutlined,
  FileOutlined,
  FolderOutlined,
  MonitorOutlined,
  SafetyOutlined,
  AuditOutlined,
  ToolOutlined,
  DashboardOutlined,
  BarChartOutlined,
  PieChartOutlined,
  LineChartOutlined,
  TableOutlined,
  FormOutlined,
  ProfileOutlined,
  UnorderedListOutlined,
  SearchOutlined,
  FilterOutlined,
  PlusOutlined,
  EditOutlined,
  DeleteOutlined,
  ReloadOutlined,
  DownloadOutlined,
  UploadOutlined,
  ExportOutlined,
  ImportOutlined,
  CheckOutlined,
  CloseOutlined,
  LockOutlined,
  UnlockOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  MailOutlined,
  PhoneOutlined,
  MessageOutlined,
  NotificationOutlined,
  BellOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  CodeOutlined,
  ConsoleSqlOutlined,
  EnvironmentOutlined,
  FileAddOutlined,
  FileTextOutlined,
  GlobalOutlined,
  HistoryOutlined,
  IdcardOutlined,
  LinkOutlined,
  MenuOutlined,
  PaperClipOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SyncOutlined,
  ApartmentOutlined,
  BranchesOutlined,
  NodeIndexOutlined,
  DeploymentUnitOutlined,
  ClusterOutlined,
  FieldNumberOutlined,
};

/** Ant Design 对外暴露的图标组件命名规则。 */
export function isSelectableIconName(name: string): boolean {
  return /(?:Outlined|Filled|TwoTone)$/.test(name);
}

/** 根据白名单解析图标；未知名称使用调用方提供的降级内容。 */
export function resolveIcon(name: string | undefined, fallback?: ReactNode): ReactNode | undefined {
  if (!name) return fallback;
  const IconComponent = iconMap[name];
  return IconComponent ? <IconComponent /> : fallback;
}

/** 为图标选择器提供受控候选集，避免动态导入整个图标包。 */
export async function loadAllIcons(): Promise<Record<string, ComponentType>> {
  return iconMap;
}
